name: CI
on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

# 여러 job이 있을경우, Default로 병렬 실행
# uses는 어떤 액션을 사용할지 지정함. 이미 만들어진 액션을 사용할 때 지정
jobs:
  docker-image-ci:
    # 어떤 OS에서 실행될지 지정
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: 100.100.103.167:5000
          username: ${{ secrets.NEXUS_ID }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            100.100.103.167:5000/kyh-test:latest
            100.100.103.167:5000/kyh-test:${{ env.RELEASE_VERSION }}

      # - name: checkout Config repository
      #   uses: actions/checkout@v2
      #   with:
      #     repository: kyh0703/GitOpsConfig
      #     token: ${{ secrets.ACTION_TOKEN }}
      #     path: GitOpsConfig


  docker-image-cd:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: kyh0703/GitOpsConfig
          token: ${{ secrets.ACTION_TOKEN }}
          path: GitOpsConfig

      - name: Commit
        run: |
          cd ./GitOpsConfig/resource/helm
          echo "sed -i -E 's/^(image[[:blank:]]*:[[:blank:]]*).*/\1100.100.103.167:5000\/kyh-test:${{ env.RELEASE_VERSION }}/' values.yaml"
          sed -i -E 's/^(image[[:blank:]]*:[[:blank:]]*).*/\1100.100.103.167:5000\/kyh-test:${{ env.RELEASE_VERSION }}/' values.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          directory: GitOpsConfig
          repository: kyh0703/GitOpsConfig
          github_token: ${{ secrets.ACTION_TOKEN }}
          force: true